plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
yarnPath: .yarn/releases/yarn-3.6.0.cjs
defaultSemverRangePrefix: ^
enableMessageNames: false
nodeLinker: node-modules
supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - linux
    - darwin
