compressionLevel: 0
defaultSemverRangePrefix: ^
enableGlobalCache: false
nodeLinker: node-modules
plugins:
  - checksum: be858e6228f8db15d5825b28a0798356a0cba9cb630f3076e76829c59af4bc8401a53b9df4bb0e45fc02bba669eeb371d258a3abf8e1a73362b5e35417485521
    path: .yarn/plugins/@yarnpkg/plugin-conventional-version.cjs
    spec: https://raw.githubusercontent.com/christophehurpeau/yarn-plugin-conventional-version/main/bundles/%40yarnpkg/plugin-conventional-version.cjs
supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - linux
    - darwin
  libc:
    - glibc
    - musl
