compressionLevel: 0

defaultSemverRangePrefix: ^

enableGlobalCache: false

enableMessageNames: false

nodeLinker: node-modules

plugins:
  - checksum: 280033c7f80a0c3ae08023a0cb96eef8b4ce4dbd123a6abf97cd3af12023dedc70390980fd54b88a52c0ed3a6eb31445aa98e5013324717399d3f2384591997e
    path: .yarn/plugins/@yarnpkg/plugin-conventional-version.cjs
    spec: "https://raw.githubusercontent.com/christophehurpeau/yarn-plugin-conventional-version/main/bundles/@yarnpkg/plugin-conventional-version.cjs"

supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - linux
    - darwin
